export const materialMasterColumns = [
  "tenant_sku_code",
  "tenant_sku_name",
  "category",
  "sub_category",
  "brand",
  "sub_brand",
  "material_group1",
  "material_group2",
  "type",
  "sub_type",
  "pack_count",
  "box_count",
  "pcs_price",
  "f_expiry_date",
];
